version: '3'

services:
  chat-server:   
    container_name: chat_server
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "9205:9205"
    restart: unless-stopped
    environment:
      - SERVER_PORT=9205
      - REDIS_ADDRESS=redis:6379
      - PRIVATE_KEY=LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1JSGNBZ0VCQkVJQUp5TDFBbVlubWUybGlpSzl1bXhYK1RsVXg1WlpPUFpxWFMwWFY4KzNsUXhtRi8zUUtsZ3YKdUFBRkZuekM1S2tKMExpTUE5aHljT1dFa29sZGh5TGNWTUNnQndZRks0RUVBQ09oZ1lrRGdZWUFCQUZ2TnFJeApOeTlUZkJtU2hmeElnOUxpWE5ZSUd4RWVIdGlkS0tMZDhyMUE0ajc0YklndW9hTStzdXlVeEM1cEpwVDd2dWx2Cld3dXdsMW1IclhFUHRuM0RPQUhvN1hJTTI4a0RQem82aS9ubnlzbENZVThwb3hKK01aZ21DMUo4MlVNRHl2QU8KNXBqVGVNQnFDdUZFQ3pFUzFhWmRtS2dEK2VRUzg2anBORTcwVzJJc21nPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQ==
  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  chat-bot-1:
    container_name: chat_bot_jim
    build:
      context: .
      dockerfile: Dockerfile.chat.bot
    environment:
      - SERVICE_HOST=chat-server
      - SERVICE_PORT=9205
      - BOT_NAME=Jim
  chat-bot-2:
    container_name: chat_bot_pam
    build:
      context: .
      dockerfile: Dockerfile.chat.bot
    environment:
      - SERVICE_HOST=chat-server
      - SERVICE_PORT=9205
      - BOT_NAME=Pam
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      - SERVICE_HOST=chat-server
      - SERVICE_PORT=9205
      - CLIENT_ID=Anonymous

